Global ("sysNamesTable", {
--  [ "sysName" ] = {Enable,"QuestType",Special}
    [ "Center_1" ] = {true,"KingdomOfElements",false},
    [ "Center_2" ] = {true,"KingdomOfElements",false},
    [ "Center_3" ] = {true,"KingdomOfElements",false},
    [ "Ice_1" ] = {true,"KingdomOfElements",false},
    [ "Ice_2" ] = {true,"KingdomOfElements",false},
    [ "Ice_3" ] = {true,"KingdomOfElements",false},
    [ "Ice_4" ] = {true,"KingdomOfElements",false}, -- "Зажигай!"
    [ "Snow_1" ] = {true,"KingdomOfElements",false},
    [ "Snow_2" ] = {true,"KingdomOfElements",false},
    [ "Snow_3" ] = {true,"KingdomOfElements",false},
    [ "Snow_4" ] = {true,"KingdomOfElements",false},
    [ "Snow_5" ] = {true,"KingdomOfElements",false},
    [ "Snow_6" ] = {true,"KingdomOfElements",false},
    [ "Snow_7" ] = {true,"KingdomOfElements",false},
    [ "Snow_8" ] = {true,"KingdomOfElements",false},
    [ "Snow_9" ] = {true,"KingdomOfElements",false},
    [ "Air_1" ] = {true,"KingdomOfElements",false},
    [ "Air_2" ] = {true,"KingdomOfElements",false},
    [ "Air_3" ] = {true,"KingdomOfElements",false},
    [ "Air_4" ] = {true,"KingdomOfElements",false},
    [ "Stone_1" ] = {true,"KingdomOfElements",false},
    [ "Stone_2" ] = {true,"KingdomOfElements",false}, -- "Каменное сердце"
    [ "Stone_3" ] = {true,"KingdomOfElements",false}, -- "Пиратская канонада"
    [ "Water_1" ] = {true,"KingdomOfElements",false},
    [ "Water_2" ] = {true,"KingdomOfElements",false},
    [ "Water_3" ] = {true,"KingdomOfElements",false},
    [ "Water_4" ] = {true,"KingdomOfElements",false}, -- "Парилка"
    [ "IM_HaloRevard" ] = {true,"Repeatable"},
    [ "MegaGoal_L_IslandDaily_07" ] = {true,"Repeatable"},
    [ "GuildQuest_1_1" ] = {true,"GuildQuest"},
    [ "GuildQuest_3_1" ] = {true,"GuildQuest"},
    [ "GuildQuest_4_1" ] = {true,"GuildQuest"},
    [ "GuildQuest_5_1" ] = {true,"GuildQuest"},
    [ "GuildQuest_2_17" ] = {true,"GuildQuest"}, -- "Обет Кары: Имперская экспедиция"
    [ "PvP_L1" ] = {true,"GuildQuest"}, -- "Окопная война"
})
