Global ("sysNamesTable", {
    [ "Center_1" ] = true,
    [ "Center_2" ] = true,
    [ "Center_3" ] = true,
    [ "Ice_1" ] = true,
    [ "Ice_2" ] = true,
    [ "Ice_3" ] = true,
    [ "Ice_4" ] = true, -- "Зажигай!"
    [ "Snow_1" ] = true,
    [ "Snow_2" ] = true,
    [ "Snow_3" ] = true,
    [ "Snow_4" ] = true,
    [ "Snow_5" ] = true,
    [ "Snow_6" ] = true,
    [ "Snow_7" ] = true,
    [ "Snow_8" ] = true,
    [ "Snow_9" ] = true,
    [ "Air_1" ] = true,
    [ "Air_2" ] = true,
    [ "Air_3" ] = true,
    [ "Air_4" ] = true,
    [ "Stone_1" ] = true,
    [ "Stone_2" ] = true, -- "Каменное сердце"
    [ "Stone_3" ] = true, -- "Пиратская канонада"
    [ "Water_1" ] = true,
    [ "Water_2" ] = true,
    [ "Water_3" ] = true,
    [ "Water_4" ] = true, -- "Парилка"
    [ "IM_HaloRevard" ] = true,
    [ "MegaGoal_L_IslandDaily_07" ] = true,
    [ "GuildQuest_1_1" ] = true,
    [ "GuildQuest_3_1" ] = true,
    [ "GuildQuest_4_1" ] = true,
    [ "GuildQuest_5_1" ] = true,
    [ "GuildQuest_2_17" ] = true,
    [ "PvP_L1" ] = true, -- "Окопная война"
})
